### ISSUE TITLE
External credits counted as courses

### ISSUE THREAD

**Issue by moinmir** [PrincetonUSG/tigerpath#464]
Adding any AP/External Credits to any semester leads to those credits being counted as courses. They reduce the overall course requirement.

**Comment by nicholaspad** [comment]
Thanks for pointing this out, but I believe it's intentional if for whatever reason you have an external credit that actually does count as a course (e.g. if you took it at another college, and Princeton approved it).

The "N/A" option is provided if you don't want the credit to be counted as a course.
<img width="361" alt="CleanShot 2022-11-07 at 15 54 39@2x" src="https://user-images.githubusercontent.com/13815069/200413415-9e0a1cad-8c94-45dd-916b-8bee346d61c1.png">
